-- Enables exclusion constraints that mix equality (staff_id) with range overlap (&&).
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    price_cents      INTEGER NOT NULL CHECK (price_cents >= 0),
    active           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE staff (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Which services each stylist can perform.
CREATE TABLE staff_services (
    staff_id   BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    PRIMARY KEY (staff_id, service_id)
);

-- Recurring weekly working hours per stylist (local salon time).
CREATE TABLE staff_availability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    day_of_week VARCHAR(16) NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,
    CHECK (end_time > start_time)
);
CREATE INDEX idx_staff_availability_staff ON staff_availability(staff_id);

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    phone      VARCHAR(64),
    google_sub VARCHAR(255) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE appointments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    staff_id    BIGINT NOT NULL REFERENCES staff(id),
    service_id  BIGINT NOT NULL REFERENCES services(id),
    start_time  TIMESTAMPTZ NOT NULL,
    end_time    TIMESTAMPTZ NOT NULL,
    status        VARCHAR(16) NOT NULL DEFAULT 'BOOKED',
    notes         TEXT,
    reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL,
    CHECK (end_time > start_time)
);

CREATE INDEX idx_appointments_staff_start ON appointments(staff_id, start_time);
CREATE INDEX idx_appointments_customer ON appointments(customer_id);

-- Hard guarantee against double-booking: no two non-cancelled appointments for the
-- same stylist may have overlapping time ranges.
ALTER TABLE appointments
    ADD CONSTRAINT no_overlapping_appointments
    EXCLUDE USING gist (
        staff_id WITH =,
        tstzrange(start_time, end_time) WITH &&
    ) WHERE (status <> 'CANCELLED');
