-- Transactional outbox: notification intents are persisted in the same transaction as the
-- booking, then delivered (with retry) by a background dispatcher. Guarantees no lost
-- confirmations even across crashes/restarts.
CREATE TABLE outbox_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient       VARCHAR(255) NOT NULL,
    subject         VARCHAR(500) NOT NULL,
    body            TEXT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at         TIMESTAMPTZ
);

-- Supports the dispatcher's poll: PENDING rows whose next_attempt_at is due.
CREATE INDEX idx_outbox_due ON outbox_notifications(status, next_attempt_at);
